### ISSUE TITLE
if the ”tf_nearest_neighbour“ is necessary for the repo ”template_ttd"

### ISSUE THREAD

**Issue by ransun1004** [jackd/tf_nearest_neighbour#1]
Hello！I am running your repo ”template_ttd". I tried to build the  tensorflow op ,but I had wrong when I compiled the operation using the command “./compile.sh",it reminded me like below：and I want to know if the ”tf_nearest_neighbour“ is necessary for the repo ”template_ttd" or not？ for your reply.

/compile.sh 
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/home/sunran/.local/lib/python3.5/site-packages/tensorflow/include/unsupported/Eigen/CXX11/../../../Eigen/src/Core/MathFunctions.h(1254): warning: calling a constexpr __host__ function("real") from a __host__ __device__ function("abs") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/home/sunran/.local/lib/python3.5/site-packages/tensorflow/include/unsupported/Eigen/CXX11/../../../Eigen/src/Core/MathFunctions.h(1254): warning: calling a constexpr __host__ function("imag") from a __host__ __device__ function("abs") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/home/sunran/.local/lib/python3.5/site-packages/tensorflow/include/unsupported/Eigen/CXX11/../../../Eigen/src/Core/MathFunctions.h(1254): warning: calling a constexpr __host__ function from a __host__ __device__ function is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/home/sunran/.local/lib/python3.5/site-packages/tensorflow/include/unsupported/Eigen/CXX11/../../../Eigen/src/Core/MathFunctions.h(1254): warning: calling a constexpr __host__ function from a __host__ __device__ function is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/home/sunran/.local/lib/python3.5/site-packages/tensorflow/include/unsupported/Eigen/CXX11/../../../Eigen/src/Core/MathFunctions.h(1259): warning: calling a constexpr __host__ function("real") from a __host__ __device__ function("abs") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/home/sunran/.local/lib/python3.5/site-packages/tensorflow/include/unsupported/Eigen/CXX11/../../../Eigen/src/Core/MathFunctions.h(1259): warning: calling a constexpr __host__ function("imag") from a __host__ __device__ function("abs") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/home/sunran/.local/lib/python3.5/site-packages/tensorflow/include/unsupported/Eigen/CXX11/../../../Eigen/src/Core/MathFunctions.h(1259): warning: calling a constexpr __host__ function from a __host__ __device__ function is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/home/sunran/.local/lib/python3.5/site-packages/tensorflow/include/unsupported/Eigen/CXX11/../../../Eigen/src/Core/MathFunctions.h(1259): warning: calling a constexpr __host__ function from a __host__ __device__ function is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/home/sunran/.local/lib/python3.5/site-packages/tensorflow/include/unsupported/Eigen/CXX11/src/Tensor/TensorRandom.h(133): warning: calling a constexpr __host__ function from a __host__ __device__ function is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/home/sunran/.local/lib/python3.5/site-packages/tensorflow/include/unsupported/Eigen/CXX11/src/Tensor/TensorRandom.h(138): warning: calling a constexpr __host__ function from a __host__ __device__ function is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/home/sunran/.local/lib/python3.5/site-packages/tensorflow/include/unsupported/Eigen/CXX11/src/Tensor/TensorRandom.h(212): warning: calling a constexpr __host__ function from a __host__ __device__ function is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/home/sunran/.local/lib/python3.5/site-packages/tensorflow/include/unsupported/Eigen/CXX11/src/Tensor/TensorRandom.h(217): warning: calling a constexpr __host__ function from a __host__ __device__ function is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/usr/bin/ld: cannot find -ltensorflow_framework

**Comment by jackd** [comment]
It is indeed necessary for template_ffd (theoretically you could re-implement the chamfer loss using a naive nearest neighbours implementation, or the kd tree implementations here, but they'd be either significantly or slightly slower). What version of tensorflow are you using? From [here](https://github.com/yuxng/DA-RNN/issues/16) is sounds like tensorflow prior to 1.4 might not work. You'll also need 1.4 for `tf.data.Dataset`s that I use in `templated_ffd`.

**Comment by ransun1004** [comment]
I am using tensorflow1.2.0，is the version too low？

**Comment by jackd** [comment]
... yeah, there's going to be issues. I mean, you could probably do a bunch of work to get around it, but the later version of tensorflow are soooo much nicer anyway. The `tf.data` module along is amazing... but that's another conversation. I'll add a note to the readme, sorry for not being explicit.

**Comment by jackd** [comment]
if you can't update to 1.8+ you'll have an issue with template_ffd's mobilenet hack... but I might fix that up shortly. If that's your only issue, don't panic, there's an easy work-around.

**Comment by jackd** [comment]
(just updated `template_ffd` so mobilenet hack should work with 1.4+)

**Comment by ransun1004** [comment]
Thank you so much for your reply, I will try the tensorflow1.4.0 first.

**Comment by ransun1004** [comment]
I updated the tensorflow version at 1.4.0 and it solved the problem of “cannot find -ltensorflow-framework”.
However,I still haven't run the file of “compile.sh ” successfully .Some warnings like this：I am so puzzled.

nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/usr/local/lib/python3.5/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/../../../Eigen/src/Core/MathFunctions.h(1265): warning: calling a constexpr __host__ function("real") from a __host__ __device__ function("abs") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/usr/local/lib/python3.5/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/../../../Eigen/src/Core/MathFunctions.h(1265): warning: calling a constexpr __host__ function("imag") from a __host__ __device__ function("abs") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/usr/local/lib/python3.5/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/../../../Eigen/src/Core/MathFunctions.h(1265): warning: calling a constexpr __host__ function from a __host__ __device__ function is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/usr/local/lib/python3.5/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/../../../Eigen/src/Core/MathFunctions.h(1265): warning: calling a constexpr __host__ function from a __host__ __device__ function is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/usr/local/lib/python3.5/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/../../../Eigen/src/Core/MathFunctions.h(1270): warning: calling a constexpr __host__ function("real") from a __host__ __device__ function("abs") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/usr/local/lib/python3.5/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/../../../Eigen/src/Core/MathFunctions.h(1270): warning: calling a constexpr __host__ function("imag") from a __host__ __device__ function("abs") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/usr/local/lib/python3.5/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/../../../Eigen/src/Core/MathFunctions.h(1270): warning: calling a constexpr __host__ function from a __host__ __device__ function is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/usr/local/lib/python3.5/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/../../../Eigen/src/Core/MathFunctions.h(1270): warning: calling a constexpr __host__ function from a __host__ __device__ function is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/usr/local/lib/python3.5/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/src/Tensor/TensorRandom.h(133): warning: calling a constexpr __host__ function from a __host__ __device__ function is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/usr/local/lib/python3.5/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/src/Tensor/TensorRandom.h(138): warning: calling a constexpr __host__ function from a __host__ __device__ function is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/usr/local/lib/python3.5/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/src/Tensor/TensorRandom.h(208): warning: calling a constexpr __host__ function from a __host__ __device__ function is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/usr/local/lib/python3.5/dist-packages/tensorflow/include/unsupported/Eigen/CXX11/src/Tensor/TensorRandom.h(213): warning: calling a constexpr __host__ function from a __host__ __device__ function is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

**Comment by jackd** [comment]
What command did you use to build tensorflow?

**Comment by ransun1004** [comment]
pip install tensorflow-gpu==1.4.0

**Comment by ransun1004** [comment]
pip install tensorflow-gpu==1.4.0

**Comment by jackd** [comment]
Almost certain you'll have to install from source. Just re-read README, should have made that clearer - it might change in future, but compiling custom ops, as far as I'm aware, still requires building from source, regardless of what op it is.

Note you'll need to add `--cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0"` to your build command.

**Comment by ransun1004** [comment]
OK, I will try it again.
By the way, My cudnn's version is 6.0, does it matter?

**Comment by jackd** [comment]
Probably not - though I usually just use the latest stable version of everything so not guaranteeing everything will work with every possible combination of other things.

**Comment by jackd** [comment]
Also haven't tested stuff with python 3, just a heads up. Mostly should be compatible, but you might need to go through and spam lots of future imports. I wrote this stuff a while ago when I was t worried about such things/was dumber, and haven't gone back through all of it to make it 2/3 compatible.

**Comment by ransun1004** [comment]
You mean you ran the code with python2? but I find that your code is based on python3?
I built the libraries in the python3 enviroment, should I change it to python 2?

**Comment by jackd** [comment]
I try to write it so it will work in both... but I only run/test python2, so python2 would be safer.

**Comment by ransun1004** [comment]
But I find some .py files in the template_ffd folder is based on python 3, is it only tf_nearest_neighbour folder on python 2?

**Comment by jackd** [comment]
... I'm unsure what you mean by "based on python 3".

**Comment by ransun1004** [comment]
I just saw some files are written by python 3, maybe I understand wrongly, you mean the whole code should be run in python 2 better, right?

**Comment by jackd** [comment]
Correct

**Comment by ransun1004** [comment]
fine, I plan to  try building a virtual environment to run the code, wish to success,Thank you so much !

**Comment by jackd** [comment]
Just a heads up: it's come to my attention recent versions of tensorflow can be installed via pip and still work with custom ops. I'm unsure when the change-over occurred. I also note the warnings you logged above are just that: warnings, not errors. If the `test_nn_distance.py` script runs successfully you should be able to ignore them.

**Comment by jackd** [comment]
Going to close this, but feel free to reopen if the problem persists.

**Comment by ransun1004** [comment]
OK，I will try it.
