### ISSUE TITLE
"g++: error: tf_nndistance_g.cu.o: No such file or directory"

### ISSUE THREAD

**Issue by JustinMBrown** [jackd/tf_nearest_neighbour#2]
When I run "sudo ./compile.sh" I get the following error message:

:~/tfnn/tf_nearest_neighbour/src$ sudo ./compile.sh
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:119] **Couldn't open CUDA library libcudnn.so. LD_LIBRARY_PATH: 
I tensorflow/stream_executor/cuda/cuda_dnn.cc:3459] Unable to load cuDNN DSO**
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:119] **Couldn't open CUDA library libcudnn.so. LD_LIBRARY_PATH: 
I tensorflow/stream_executor/cuda/cuda_dnn.cc:3459] Unable to load cuDNN DSO**
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
**./compile.sh: 4: ./compile.sh: /bin/nvcc: not found
g++: error: tf_nndistance_g.cu.o: No such file or directory**

I definitely have cuda and cuDNN installed. Here are some other commands to show my setup:

:~/tfnn/tf_nearest_neighbour/src$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176

:~/tfnn/tf_nearest_neighbour/src$ which nvcc
/usr/local/cuda/bin/nvcc

:~/tfnn/tf_nearest_neighbour/src$ printenv | grep CUDA
CUDA_HOME=/usr/local/cuda

:~/tfnn/tf_nearest_neighbour/src$ printenv | grep LD_L
LD_LIBRARY_PATH=:/usr/local/cuda/extras/CUPTI/lib64

Any ideas on what the problem could be?

**Comment by jackd** [comment]
Looks like it can't find `nvcc`. Do you have you `CUDA_HOME` variable set? Try `export CUDA_HOME=/usr/local/cuda` (or wherever it is - it's normally just a link to `/usr/local/cuda-X-X`). I have `nvcc` binary at `/usr/local/cuda/bin/nvcc`, but depending on how you installed everything it could be somewhere else...

I've also just tried building with the latest version of tensorflow (1.10) and seem to have some issues. Let me know if you're in the same boat. Not sure on a solution at this stage, though a sub-optimal work-around for the time being might be to use `tf <= 1.9`...

**Comment by jackd** [comment]
Update: ok, I had a typo in a local edit. Build should work with tf 1.10. :)

**Comment by JustinMBrown** [comment]
Yes I have those environment variables set. From the OP:

:~/tfnn/tf_nearest_neighbour/src$ which nvcc
**/usr/local/cuda/bin/nvcc**

:~/tfnn/tf_nearest_neighbour/src$ printenv | grep CUDA
**CUDA_HOME=/usr/local/cuda**

:~/tfnn/tf_nearest_neighbour/src$ printenv | grep LD_L
**LD_LIBRARY_PATH=:/usr/local/cuda/extras/CUPTI/lib64**

What does your LD_LIBRARY_ PATH look like? The error seems to hint that's where the problem is.

Also, I am using tf 1.10, and I updated to your newest version, but I'm still getting the same error.

**Comment by JustinMBrown** [comment]
I went ahead and just hard coded the path to nvcc in the compile.sh, and that seemed to fix the original error. Now I'm getting an error about gcc versions later than 6 not being supported.

Where exactly do you add `--cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0"` in order to get around the gcc version problem?

Btw, I'm on ubuntu 18.04

**Comment by jackd** [comment]
That nvcc path has me thoroughly bemused... but sounds like its been resolved, so I'll file that under "magic I don't need to understand."

If it helps: my `LD_LIBRARY_PATH` is
:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/lib/nvidia-384

I've only tested on 16.04 and gcc 5.4. I'm guessing 18.04 still has `g++-5`, but `g++` is almost certainly linked to version 6. Can you try changing `g++` to `g++-5` in your `compile.sh` and let me know if that resolves things? I don't have an 18.04 box available for testing, but I'm guessing the setup is similar to 16.04.

If that doesn't work, maybe check what's in your /usr/bin: `ls /usr/bin | grep g++`.

I'm not sure if the `--cxxopt` section is relevant any more. It's still on the "building an op" page, so I'll leave a note in the README for now, but might put some disclaimer around it similar to this one. Originally custom ops could only be used if you built tensorflow from source. I just installed the latest nightly version via pip (`pip install tf-nightly-gpu`) and things seems to work fine. The `--cxxopt` was for when you built tensorflow.

**Comment by jackd** [comment]
I've pushed an update which changes `g++` to `g++-5` (shouldn't make a difference on 16.04 and I'm assuming 18.04 still has g++-5 on path by default). I'm guessing this is resolved, but feel free to re-open if you still have trouble.
